name: Deployment to SIT

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  Deployment:
    name: Deploying to the SIT org
    runs-on: ubuntu-latest
    container: salesforce/cli:latest-rc-slim

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Starting deployment to SIT ...
        run: echo "Deployment process to SIT will be executed here."

      - name: Login to SIT org
        run: |
          echo ${{ secrets.VALIDATE_ORG_SFDX_AUTH_URL }} > ./VALIDATE_ORG_SFDX_AUTH_URL.txt
          sf org login sfdx-url -f ./VALIDATE_ORG_SFDX_AUTH_URL.txt --alias SitOrg
  
      - name: Deploying source code through manifest/package.xml
        run: sf project deploy start -x manifest/package.xml --target-org SitOrg --test-level RunLocalTests
        
      # - name: SFDX Auth
      #   env:
      #     SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY }}
      #     SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
      #   run: |
      #     echo "${SFDX_JWT_KEY}" > server.key
      #     sf org login jwt --client-id "${SFDX_CLIENT_ID}" --jwt-key-file server.key --username jitendras@lwr.com --alias sitOrg --instance-url=https://login.salesforce.com
      #     rm server.key
      #     sf project deploy start -x manifest/package.xml --target-org sitOrg
      #     echo Deployment completed successfully