name: Environment variables

on: 
  push:
    branches: [master]

env:
  ORG: Development
  
jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Display environment variable value
      run: |
        echo "Org name (job1): $ORG"

  job2:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Job2 environment variable value
      run: |
        echo "Org name (job2): $ORG"