name: Pipeline implementation

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
#    container: salesforce/cli:latest-rc-slim
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Check if there is some destructive changes
      run: |
        if [ -f destructiveChanges/cpd/destructiveChangesPost.xml ]; then
          echo "Destructives changes file exists"
          grep -q '<members>' destructiveChanges/cpd/destructiveChangesPost.xml; greprc=$?
          if [ $greprc -eq 0 ]; then
            echo "There are components to delete"
          fi
        else
          echo "Destructives changes file does NOT exist"
        fi

    - name: Check the current branch
      run: |
        CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
        if [ $CURRENT_BRANCH = "master" ]; then
          echo "Deploys from the master branch"
        else
          echo "Deploys from the current branch"
        fi



#    - name: Configure devhub org
#      run: |
#        echo ${{ secrets.DEVHUB_SFDX_URL }} > ./SFDX_URL_STORE.txt
#        sf org login sfdx-url -f ./SFDX_URL_STORE.txt -a devhub -d

#    - name: Creating a new scratch org ...
#      run: sf org create scratch -d -f config/project-scratch-def.json --duration-days 1 --alias sOrg31Jan24

#    - name: Deploying all source code to the scratch org
#      run: sf project deploy start -x manifest/package.xml --target-org sOrg31Jan24 --test-level RunAllTestsInOrg

#    - name: Deleting the scratch org
#      run: sf org delete scratch -o sOrg31Jan24 -p