name: Pipeline implementation

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    container: salesforce/cli:latest-rc-slim
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - name: Create a scratch org
      run: sf org create scratch --definition-file config/project-scratch-def.json --alias sOrg31Jan24 --target-dev-hub jitendras@lightning.com